# Generated by Django 5.1.3 on 2025-01-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="nickname",
            new_name="username",
        ),
    ]
