# Generated by Django 5.1.3 on 2025-01-15 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_workhistory_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='level',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
