# Generated by Django 5.1.3 on 2024-12-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='skill_reference',
        ),
        migrations.AddField(
            model_name='userskill',
            name='skill_reference',
            field=models.ManyToManyField(related_name='related_skill', to='profiles.skill'),
        ),
    ]
