# Generated by Django 5.1.3 on 2024-12-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userskill_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='gitbe',
            new_name='website',
        ),
    ]
