# Generated by Django 5.1.3 on 2025-01-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_profile_city_alter_profile_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="profile_image",
        ),
    ]
