# Generated by Django 5.1.3 on 2025-01-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_remove_profile_slug_id_remove_profile_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="workhistory",
            name="is_working",
            field=models.BooleanField(default=False),
        ),
    ]
