version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      timeout: 3s

  django:
    container_name: django
    build:
      context: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "8001:8000"
    env_file:
      - .env.local
    depends_on:
      redis:
        condition: service_healthy

  celery:
    container_name: celery
    build:
      context: .
    restart: always
    command: celery -A core.celery worker --loglevel=info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.local
    depends_on:
      redis:
        condition: service_healthy
      django:
        condition: service_started
