# Generated by Django 5.1.3 on 2024-12-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobRequest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrequest",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
