# Generated by Django 5.1.3 on 2025-01-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_userdeviceinfo_screen_resolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdeviceinfo',
            name='ip_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
