# Generated by Django 5.1.3 on 2025-02-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
