# Generated by Django 5.1.3 on 2025-02-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='slug_id',
            field=models.SlugField(blank=True, default='f27f3d04', max_length=8, unique=True),
        ),
    ]
