# Generated by Django 5.1.3 on 2025-02-21 14:49

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.SlugField(blank=True, default=base.utils.generate_unique_id, editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('job_image', models.ImageField(blank=True, null=True, upload_to='job_images/')),
                ('description', models.TextField()),
                ('time', models.IntegerField()),
                ('is_approve', models.BooleanField(default=False)),
                ('is_register', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ایده ها',
                'verbose_name_plural': 'ایده ها',
            },
        ),
        migrations.CreateModel(
            name='SkillNeeded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.SlugField(blank=True, default=base.utils.generate_unique_id, editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'مهارت های مورد نیاز',
                'verbose_name_plural': 'مهارت های مورد نیاز',
            },
        ),
    ]
